chore: update PostgreSQL driver to 42.2.14
v42.2.15 and newer cause the below exception originating from the driver in tests:
org.postgresql.util.PSQLException: ERROR: invalid input syntax for type bigint: "[J@53ec2968"


Former-commit-id: 7e465a5886b512826f6203fe19edd6a8e56865c2